package com.iya.rental.enums;

public enum StatusCode {
    OK,
    ERROR,
    FAILED,
    DATA_NOT_FOUND,
    SAVE_BOOKING_ERROR,
    CANCEL_BOOKING_NOT_FOUND,
    CANCEL_SLOT_ERROR,
    CANCEL_SLOT_NOT_FOUND,
    TRANSACTION_NOT_FOUND,
    UNAUTHORIZED,
    CHECK_SLOT_FAILED,
    CHECK_SLOT_ERROR,
    APPLY_VOUCHER_ERROR,
    VEHICLE_NOT_FOUND,
    CONSUMER_NOT_FOUND,
    PROFORMA_INVOICE_ERROR,
    CANCEL_VOUCHER_ERROR,
    CANCEL_APPLY_VOUCHER_ERROR;
}
