# server:
#   port: 8081
#   tomcat:
#     connection-timeout: 1000000
  
spring:
  datasource:
    url: jdbc:mysql://${DBHOST:localhost}:${DBPORT:3306}/rental?serverTimezone=Asia/Jakarta&verifyServerCertificate=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mitrais
    tomcat:
      validation-query: SELECT 1
      validation-query-timeout: 3000
      test-on-borrow: true
      test-on-connect: true
  jpa: 
    database: MYSQL
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.improvedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect